### ISSUE TITLE
boto issue: Can't use S3 bucket names with dots

### ISSUE THREAD

**Issue by jheasly** [registerguard/ap_wfm#37]
[Here's](https://github.com/boto/boto/issues/2836#issuecomment-108791127) the fix!

Struggled with this for a few days. (Don't bother with the #3163 PR/patch!)

**Comment by 7heo** [comment]
@jheasly The PR 3163 is supposed to fix the issue without hardcoding any value. Fixing an issue with a config file is a pretty bad practice. I would recommend to re-open the issue and fix it properly; rather than masking the problem with an ugly hack.
